version: "3"
services:
  hub:
    image: selenium/hub:3.12.0
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome-debug
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub

  firefox:
    image: selenium/node-firefox:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      
  login-module:
    image:sandocker100/selenium-docker-test-maven:latest
    depends_on:
      - chrome
      - firefox
    environment:
      - MODULE=testng.xml
      - BROWSER=chrome
      - HUB_HOST=143.244.176.53
    volumes:
      - /home/user/test_result_chrome:/usr/share/udemy/test-output

  search-module:
    image:sandocker100/selenium-docker-test-maven:latest
    depends_on:
      - chrome
      - firefox
    environment:
      - MODULE=testng.xml
      - BROWSER=firefox
      - HUB_HOST=143.244.176.53
    volumes:
      - /home/user/test_result_firefox:/usr/share/udemy/test-output
